//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "LoadSceneMenuFileGenerator".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using UnityEditor.SceneManagement;

namespace Assets.Scripts.LoadingSystems.Editor.LoadMenuGenerations
{
    public static partial class CustomMenu
    {
    }
}