//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneClassesGeneration".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    public partial class SceneInfo
    {
		private static Dictionary<SceneId, SceneInfo> _registry = new Dictionary<SceneId, SceneInfo>()
        {
        };
    }
}