//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneInfoGenerator".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    public partial class SceneInfo
    {
		private static Dictionary<SceneId, SceneInfo> _registry = new Dictionary<SceneId, SceneInfo>()
        {
			{SceneId._0_Gameplay, new SceneInfo(SceneId._0_Gameplay, "0-Gameplay", SceneType.Gameplay)},
			{SceneId._1_1_TransitionCorridorRoom, new SceneInfo(SceneId._1_1_TransitionCorridorRoom, "1-1-TransitionCorridorRoom", SceneType.Room)},
			{SceneId._1_WakeUpRoom, new SceneInfo(SceneId._1_WakeUpRoom, "1-WakeUpRoom", SceneType.Room)},
			{SceneId._3_1_CorridorRoom, new SceneInfo(SceneId._3_1_CorridorRoom, "3-1-CorridorRoom", SceneType.Room)},
			{SceneId._3_2_CorridorRoom, new SceneInfo(SceneId._3_2_CorridorRoom, "3-2-CorridorRoom", SceneType.Room)},
			{SceneId._3_HubRoom, new SceneInfo(SceneId._3_HubRoom, "3-HubRoom", SceneType.Room)},
			{SceneId._4_1_LabAccessRoom, new SceneInfo(SceneId._4_1_LabAccessRoom, "4-1-LabAccessRoom", SceneType.Room)},
			{SceneId._4_LabRoom, new SceneInfo(SceneId._4_LabRoom, "4-LabRoom", SceneType.Room)},
			{SceneId.MasterScene, new SceneInfo(SceneId.MasterScene, "MasterScene", SceneType.Master)},
			            
        };
    }
}