//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneInfoGenerator".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    public enum SceneId
    {

    }
}