//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by "SceneClassesGeneration".
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Assets.Scripts.LoadingSystems.SceneInfos
{
    /// <summary>
    /// Enumeration identifying scenes in the system.
    /// </summary>
    public enum SceneId
    {
    }
}